[project]
name = "mcp-gitbook"
version = "0.1.0"
description = "An MCP server using FastMCP"
requires-python = ">=3.8"
dependencies = [
    "mcp[cli]",
    "requests",
    "python-dotenv"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"